### ISSUE TITLE
Incorrect Usage example in README

### ISSUE THREAD

**Issue by Marcono1234** [joschi/java-metadata#1]
The README says:
>You can fetch the latest metadata for all Zulu Community™ releases at the following URL:
>```
>https://joschi.github.io/java-metadata/metadata/all.json
>```

However, it appears that API end-point returns releases from all vendors, not only from Zulu Community™.

**Comment by joschi** [comment]
@Marcono1234 Thanks a lot, I fixed the sentence. 👍
