### ISSUE TITLE
Corretto 17 is not available

### ISSUE THREAD

**Issue by bric3** [joschi/java-metadata#17]
I noticed that asdf java does not list Corretto 17. Indeed when I look at the available metadata it's not listed either.

Reprocucer

```shell
$ curl -X 'GET' 'https://joschi.github.io/java-metadata/metadata/ga/linux/x86_64/jdk/hotspot/corretto.json' -H 'accept: application/json' | jq '.[].java_version' | grep "17\."
```

Releases have been available for 4days at the time of this issue creation.
https://github.com/corretto/corretto-17/releases

**Comment by bric3** [comment]
Just for reference the current workaround is

```shell
$ cd ~/.asdf/installs/java
$ curl -LO https://corretto.aws/downloads/resources/17.0.0.35.2/amazon-corretto-17.0.0.35.2-macosx-x64.tar.gz
$ mkdir -p corretto-17.0.0.35.2; tar --strip-components=3 -C corretto-17.0.0.35.2/ -xf amazon-corretto-17.0.0.35.2-macosx-x64.tar.gz amazon-corretto-17.jdk/Contents/Home && asdf reshim java
$ rm -rf amazon-corretto-17.jdk amazon-corretto-17.0.0.35.2-macosx-x64.tar.gz
```

**Comment by joschi** [comment]
@bric3 Thanks for reporting this and contributing the pull request to fix the issue!

Metadata for Corretto 17 has been added in https://github.com/joschi/java-metadata/commit/effab23ab2f60a57262ab9683b51c158d0d3449f.
