### ISSUE TITLE
file_type description in README is incomplete

### ISSUE THREAD

**Issue by Marcono1234** [joschi/java-metadata#2]
The README currently says:
>| Field name     | Description                           |
>| -------------- | ------------------------------------- |
>| `file_type`    | `tar.gz`, `zip`, `dmg`, `msi`         |

However, it appears it also returns these other file types (list might be incomplete):
- `rpm`
- `deb`

**Comment by joschi** [comment]
@Marcono1234 Thanks! I've fixed the description.

While `tar.gz`, `zip`, etc. are the most common file extensions, the list wasn't meant to be exhaustive.
