### ISSUE TITLE
amazon-corretto-18.0.2.9.1-macosx-aarch64.tar.gz has wrong checksum

### ISSUE THREAD

**Issue by jdxcode** [joschi/java-metadata#29]
The checksum for amazon-corretto-18.0.2.9.1-macosx-aarch64.tar.gz is wrong:

```
❯ curl https://corretto.aws/downloads/resources/18.0.2.9.1/amazon-corretto-18.0.2.9.1-macosx-aarch64.tar.gz | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  178M  100  178M    0     0  34.1M      0  0:00:05  0:00:05 --:--:-- 37.5M
f003000033a25d0ce8f00adfc1b88935da0d330b0ab5587c520f793869415462  -
❯ curl https://joschi.github.io/java-metadata/checksums/corretto/amazon-corretto-18.0.2.9.1-macosx-aarch64.tar.gz.sha256
a2a25da58e280e762397ab5bf815833690ab0f9d9531da97c471a57428c479b2  amazon-corretto-18.0.2.9.1-macosx-aarch64.tar.gz
```

Also see https://github.com/corretto/corretto-18/releases/tag/18.0.2.9.1

**Comment by rschmitt** [comment]
Can confirm, I'm the original reporter

**Comment by joschi** [comment]
@jdxcode @rschmitt Thanks for reporting this!

I've removed the artifacts for Corretto 18.0.2.9.1 so that they will be downloaded again.

**Comment by joschi** [comment]
The checksums are correct now:
https://github.com/joschi/java-metadata/blob/e8419607ec9a1938a96a26d2740507352d5bee93/docs/checksums/corretto/amazon-corretto-18.0.2.9.1-macosx-aarch64.tar.gz.sha256
