### ISSUE TITLE
AdoptOpenJDK 15 is not listed

### ISSUE THREAD

**Issue by bric3** [joschi/java-metadata#3]
I am using asdf as a package manager, and I noticed that AdoptOpenJDK 15 is not listed. I know that asdf java plugin rely on this metadata site to generate its listing. So while inspecting the output, I notice the JDK 15 is not listed in the following output :

```
curl -X GET "https://joschi.github.io/java-metadata/metadata/ga/macosx/x86_64/jdk/hotspot/adoptopenjdk.json" -H  "accept: application/json"
```

* https://adoptopenjdk.net/?variant=openjdk15&jvmVariant=hotspot
* https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/tag/jdk-15+36

**Comment by bric3** [comment]
I don't know why but the actions logs reveal that the update script of AdoptOpenJDK does not pickup 15 
https://github.com/joschi/java-metadata/runs/1122605736?check_suite_focus=true#step:4:29

While the AdoptOpenJDK, have it : 

```shell
$  curl -L https://api.adoptopenjdk.net/v3/info/available_releases

{
    "available_lts_releases": [
        8,
        11
    ],
    "available_releases": [
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15
    ],
    "most_recent_feature_release": 15,
    "most_recent_feature_version": 15,
    "most_recent_lts": 11,
    "tip_version": 16
}%
```

**Comment by bric3** [comment]
Maybe it's a timing issue : https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/tag/jdk-15+36 was released 3 hours ago, and the AdoptOpenJDK API wasn't up to date when this github actions ran.

**Comment by joschi** [comment]
AdoptOpenJDK 15 (as well as some other JREs/JDKs) have been added in 8e32aae998c4c3e1b8bae497fadecefed5b31a91.
