### ISSUE TITLE
Bad data: unknown architecture

### ISSUE THREAD

**Issue by jdx** [joschi/java-metadata#35]
There are some bad releases added in the latest commit that are causing some problems for me with null values

https://github.com/joschi/java-metadata/commit/d2d2a425008f5349946cb78aa15b58f443d502c2

https://github.com/joschi/java-metadata/blob/main/docs/metadata/ea/aix/unknown-architecture-/jdk.json

**Comment by joschi** [comment]
@jdx Thanks for reporting this. ❤️ 

The fix and cleanup were in https://github.com/joschi/java-metadata/commit/b4c031958de2de5168c15fa8281668ba7ceab2fd and https://github.com/joschi/java-metadata/commit/2483deb71c5f360f736c528c42a41d67d1917bed respectively.
