### ISSUE TITLE
Zulu 8.76.0.17 missing

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [joschi/java-metadata#40]
Hello,

The Azul Zulu version 8.76.0.17 is missing from the list.
Per https://static.azul.com/zulu/bin it was recently released (2024-01-10).

**Comment by joschi** [comment]
@aleksandrs-ledovskis Thanks for reporting this!

It looks like the HTML page we're scraping the information from changed their format some time ago.

This should be fixed in the next update run.

**Comment by joschi** [comment]
✅ https://github.com/search?q=repo%3Ajoschi/java-metadata%20path%3Azulu8.76.0.17&type=code

**Comment by aleksandrs-ledovskis** [comment]
Thanks!
