### ISSUE TITLE
Oracle JDK and Oracle GraalVM version details seem to have moved.

### ISSUE THREAD

**Issue by smarr** [joschi/java-metadata#44]
It looks like https://www.oracle.com/java/technologies/downloads/ is now the go-to place for recent "script-friendly" URLs for releases.

While https://www.oracle.com/java/technologies/javase/graalvm-jdk21-archive-downloads.html exists, the latest https://www.oracle.com/java/technologies/javase/graalvm-jdk22-archive-downloads.html doesn't exist (or doesn't exist yet).

Not sure what the preferred way of handling this would be, but I could attempt to put a PR together to add support for the new overview page to extract version info.
I guess it would probably go in here? https://github.com/joschi/java-metadata/blob/main/bin/oracle-graalvm.bash

Guidance on how best to handle this change is welcome.

Thanks!

**Comment by joschi** [comment]
@smarr Thanks for reporting this issue! I've implemented fetching the latest releases of Oracle JDK and GraalVM as well in the respective providers.

Too bad Oracle doesn't provide a complete machine-readable list of their releases. 😞

**Comment by smarr** [comment]
Thanks. Yeah, it's also a bit all over the place.
There's for instance also still the early releases here: https://github.com/graalvm/oracle-graalvm-ea-builds/releases

**Comment by joschi** [comment]
> There's for instance also still the early releases here: https://github.com/graalvm/oracle-graalvm-ea-builds/releases

They're already covered via https://github.com/joschi/java-metadata/blob/e38f7dc57d422dd7a3653f89573727bb3ce24e04/bin/oracle-graalvm-ea.bash. 😉
