### ISSUE TITLE
OpenJDK Loom 23/24 should be EA release type

### ISSUE THREAD

**Issue by roele** [joschi/java-metadata#51]
The `loom` versions of OpenJDK `23` and `24` should be `release_type: ea`.

Culprit seems to be a copy/paste issue in
https://github.com/joschi/java-metadata/blob/b295eec224755c7c5bd71c97610068201b2504e5/bin/openjdk-loom.bash#L26

**Comment by joschi** [comment]
@roele Thanks for reporting this! ❤️
