### ISSUE TITLE
What about adding IBM JDKs?

### ISSUE THREAD

**Issue by amandel** [joschi/java-metadata#54]
I know these are only old JDKs but still valuable for Websphere Application Server related development.

The JDKs are today available below https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/ for 8.0.x, 7.1.x and 7.0.x

**Comment by joschi** [comment]
I'm happy to merge any pull request adding these older JDKs but I don't currently have the bandwidth to work on this myself.

@amandel Do you want to give this a shot?
